spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/data-store?currentSchema=admin"
    username: admin
    password: admin
    hikari:
      maximum-pool-size: 2
    driver-class-name: org.postgresql.Driver

  application:
    name: "Table_cleanup_agent_application"


#записи старше x часов.
hours: 5


#Название таблицы
tableNameSqlParam: external_app_stat

#Наименование поля с первичным ключом
primalKeyColumnDelSqlParam: id


#Наименование поля в таблице в котором, временная метка создания записи
timeStampOfRecordCreation: time
limitDelSqlParam: 3

#Период выборки строк из таблицы, подлежащих удалению
deletionPeriodArgument: "10 * * * * *" #3 раза в час
samplingPeriodArgument: "0 * * * * *" #10 раз в час

logging:
  config: classpath:log4j.yaml