spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/data-store?currentSchema=admin"
    username: admin
    password: admin
    hikari:
      maximum-pool-size: 2
    driver-class-name: org.postgresql.Driver

  application:
    name: "Table_cleanup_agent_application"


#записи старше x часов.
hours: 5

#Аргумент условия для выборки элементов в SQL запросе Delete
conditionForSampling: id

#Название таблицы
tableNameSqlParam: external_app_stat

#Наименование поля с первичным ключом
primalKeyColumnDelSqlParam: id

#Арифметический знак
thirdArithmeticSignDelSqlParam: =



#Наименование поля в таблице в котором, временная метка создания записи
timeStampOfRecordCreation: time

#Количество удаляемых записей за одну итерацию
limitDelSqlParam: 3

#Период выборки строк из таблицы, подлежащих удалению
deletionPeriodArgument: "10 * * * * *"

samplingPeriodArgument: "0 * * * * *"

#Задержка удаления
delayedRemoval: 1


logging:
  config: classpath:log4j.yaml